// Code generated by mockery v2.30.1. DO NOT EDIT.

package component

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSyncComponentWithLoading is an autogenerated mock type for the SyncComponentWithLoading type
type MockSyncComponentWithLoading[V interface{}, T interface{}] struct {
	mock.Mock
}

// ExecuteSync provides a mock function with given fields: ctx, data
func (_m *MockSyncComponentWithLoading[V, T]) ExecuteSync(ctx context.Context, data LoadData[V]) (T, error) {
	ret := _m.Called(ctx, data)

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, LoadData[V]) (T, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, LoadData[V]) T); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(T)
	}

	if rf, ok := ret.Get(1).(func(context.Context, LoadData[V]) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Load provides a mock function with given fields: ctx
func (_m *MockSyncComponentWithLoading[V, T]) Load(ctx context.Context) (V, error) {
	ret := _m.Called(ctx)

	var r0 V
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (V, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) V); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(V)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockSyncComponentWithLoading creates a new instance of MockSyncComponentWithLoading. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSyncComponentWithLoading[V interface{}, T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSyncComponentWithLoading[V, T] {
	mock := &MockSyncComponentWithLoading[V, T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
