// Code generated by mockery v2.30.1. DO NOT EDIT.

package component

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIExecutor is an autogenerated mock type for the IExecutor type
type MockIExecutor struct {
	mock.Mock
}

// InvokeExecutingTask provides a mock function with given fields: ctx
func (_m *MockIExecutor) InvokeExecutingTask(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// canBeInvokedAsync provides a mock function with given fields:
func (_m *MockIExecutor) canBeInvokedAsync() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// cancel provides a mock function with given fields: err
func (_m *MockIExecutor) cancel(err error) {
	_m.Called(err)
}

// invokeAsyncTask provides a mock function with given fields: ctx
func (_m *MockIExecutor) invokeAsyncTask(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// invokeSyncTask provides a mock function with given fields: ctx
func (_m *MockIExecutor) invokeSyncTask(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockIExecutor creates a new instance of MockIExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIExecutor {
	mock := &MockIExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
